const camName =   ["Look Rock", 
                "Purchase Knob", 
                "Cold Mountain", 
                "New Found Gap", 
                "Joyce Kilmer",
                "Clingmans Dome",
                "Mammoth Cave", 
                "Jackson",
                "Robinson Forest"],
    camActive = [true, true, false, true, false, true, true, true, true],
    camCoords = [[35.633424, -83.941254],
                [35.585966, -83.072944],
                [35.393713, -82.774422],
                [35.611073, -83.424583],
                [35.257497, -83.795160],
                [35.562709, -83.498421],
                [37.192755, -86.102055],
                [37.592006, -83.316127],
                [37.467008, -83.157612]],
    camLoRes =    ["https://www.outragegis.com/weather/img/LookRock-400.jpg",
                "https://www.outragegis.com/weather/img/PurchaseKnob-400.jpg",
                "https://www.outragegis.com/weather/img/ColdMountain-400.jpg",
                "https://www.outragegis.com/weather/img/NewGap-400.jpg",
                "https://www.outragegis.com/weather/img/JoyceKilmer-400.jpg",
                "https://phenocam.sr.unh.edu/data/latest/thumbs/smokydome.thumb.jpg",
                "https://www.outragegis.com/weather/img/MaCa-400.jpg",
                "https://www.outragegis.com/weather/img/DBoone-400.jpg",
                "https://phenocam.sr.unh.edu/data/latest/thumbs/robinson2.thumb.jpg"],
    camHiRes =  ["https://www.outragegis.com/weather/img/LookRock.jpg",
                 "https://www.outragegis.com/weather/img/PurchaseKnob.jpg",
                 "https://www.outragegis.com/weather/img/ColdMountain.jpg",
                 "https://www.outragegis.com/weather/img/NewGap.jpg",
                 "http://www.outragegis.com/weather/img/JoyceKilmer.html",
                 "https://phenocam.sr.unh.edu/data/latest/smokydome.jpg",
                 "https://www.outragegis.com/weather/img/MaCa.jpg",
                 "https://www.outragegis.com/weather/img/DBoone-Lg.jpg",
                 "https://phenocam.sr.unh.edu/data/latest/robinson2.jpg"]
    camInfo =   ["East", "East", "West", "South", "West", "North", "North", "South", "West"],
    camElev =   [2628, 5085, 4922, 5046, 4801, 6644, 741, 1400, 1585];